In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

print("Array a:", a)
print("Array b:\n", b)


Array a: [1 2 3]
Array b:
 [[1 2 3]
 [4 5 6]]


In [4]:
print("Shape of b:", b.shape)
print("First row:", b[0])
print("Element at (1,2):", b[1,2])

Shape of b: (2, 3)
First row: [1 2 3]
Element at (1,2): 6


In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print("Sum:", x+y)
print("Element-wise square:", x **2)
print("Dot product:", np.dot(x,y))

Sum: [5 7 9]
Element-wise square: [1 4 9]
Dot product: 32


In [10]:
zeros = np.zeros((2,3))
ones = np.ones((3,3))
range_arr = np.arange(10)
linspace_arr = np.linspace(0,1,5)

print("Zeros:\n", zeros)
print("Linspace:", linspace_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [12]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

C = np.dot(A,B)
print("Matirx multiplication result:\n", C)

Matirx multiplication result:
 [[19 22]
 [43 50]]
